CREATE TABLE journal
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                             NOT NULL,
    description TEXT                                     NOT NULL,
    start_date  date                                     NOT NULL,
    end_date    date                                     NOT NULL,
    visibility  VARCHAR(255)                             NOT NULL,
    user_id     INTEGER                                  NOT NULL,
    CONSTRAINT pk_journal PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                             NOT NULL,
    surname  VARCHAR(255)                             NOT NULL,
    email    VARCHAR(255)                             NOT NULL,
    password VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE journal
    ADD CONSTRAINT FK_JOURNAL_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);