CREATE TABLE journal_entry
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entry_date DATE                                    NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    content    TEXT                                    NOT NULL,
    mood       VARCHAR(255),
    weather    VARCHAR(255),
    journal_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_journal_entry PRIMARY KEY (id)
);

ALTER TABLE journal_entry
    ADD CONSTRAINT fk_journal_entry_on_journal
        FOREIGN KEY (journal_id) REFERENCES journal (id);
